version: "2"
services:
  api:
    container_name: users-crud-api
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    container_name: users-crud-frontend
    ports: 
      - "80:80"
    links:
      - api